apiVersion: v1
kind: Service
metadata:
  name: grpc-project-x
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: grpc-project-x
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-project-x
spec:
  selector:
    matchLabels:
      app: grpc-project-x
  template:
    metadata:
      labels:
        app: grpc-project-x
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: grpc-project-x-key
      - name: cloudsql-pw
        secret:
          secretName: cloudsql-pw
      containers:
      - name: goserver
        image: gcr.io/mytests-262609/goserver:4.0
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
        - name: cloudsql-pw
          mountPath: /var/secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLOUDSQL_ROOT_CREDENTIALS
          value: /var/secrets/rootPw
        - name: INSTANCE
          valueFrom:
            configMapKeyRef:
                name: myconfigmap
                key: cloudSqlInstance